### ISSUE TITLE
Deployed spiders disappear after few hours

### ISSUE THREAD

**Issue by ddfsdd** [my8100/scrapyd-cluster-on-heroku#14]
After deploying the scrapyd and scrapydweb to heroku, I try to deploy a spider and this works perfectly normal; however, after certain hours, the application refreshes and my spiders disappear. Is there a workaround to this issue?
Thank you very much

**Comment by my8100** [comment]
See https://github.com/my8100/scrapyd-cluster-on-heroku/blob/master/README.md#conclusion
