### ISSUE TITLE
About Redis Labs account

### ISSUE THREAD

**Issue by Cally99** [my8100/scrapyd-cluster-on-heroku#5]
Hi there, I'd like to ask a question on this cool repo for Scrapy.

I was wondering do you select cache or standard when signing up for redis-labs.

I'm a bit reluctant to put my credit card details into an account with redis. If I was running two spiders on a daily crawl three times a day would I exceed the 30mb after say 1 month?

Is it possible to use this repo with heroku hosting only?

Thanks
Tom

**Comment by my8100** [comment]
> I was wondering do you select cache or standard when signing up for redis-labs.
> I'm a bit reluctant to put my credit card details into an account with redis. 

There's no need to provide a credit card when I created a FREE TRIAL account on Redis Labs,
as the screenshot [here](https://github.com/my8100/scrapyd-cluster-on-heroku#create-accounts) shows.

> If I was running two spiders on a daily crawl three times a day would I exceed the 30mb after say 1 month?

It depends on how your spiders use Redis.

> Is it possible to use this repo with heroku hosting only?

Creating an account on Redis Labs is optional unless you are using [scrapy-redis](https://github.com/rmax/scrapy-redis) for distributed crawling.
