### ISSUE TITLE
how to specify python version and requirements.txt

### ISSUE THREAD

**Issue by my8100** [my8100/scrapyd-cluster-on-heroku#6]
https://github.com/my8100/scrapydweb/issues/87#issue-482560848

> Thanks for working on this great project. I have followed your instructions to setup scrapyd and scrapydweb on heroku, but ran into issue that there are other package dependencies in my scrapy project such as sqlalchemy.
> 
> When I deploy to scrapinghub.com, I specify that in the scrapinghub.yml in my project as follows:
> 
> ```yaml
> project: 404937
> 
> stacks:
>     default: scrapy:1.7-py3
> requirements:
>   file: requirements.txt
> ```
> 
> How to do this for Scrapydweb?
> 
> Thanks a lot!

**Comment by my8100** [comment]
@harrywang
Try [custom-deployment](https://github.com/my8100/scrapyd-cluster-on-heroku#custom-deployment) instead and update [runtime.txt](https://github.com/my8100/scrapyd-cluster-on-heroku/blob/master/scrapyd/runtime.txt) and [requirements.txt](https://github.com/my8100/scrapyd-cluster-on-heroku/blob/master/scrapyd/requirements.txt) as needed.

**Comment by harrywang** [comment]
thanks for the quick answer!
